#!/usr/bin/env ruby

if ARGV.empty?
  script = File.basename($PROGRAM_NAME)
  puts "Usage: #{script} directory"
  exit 1
end

year = File.basename(ARGV[0])
if year !~ /^\d{4}$/
  puts "error: directory is not valid (yyyy)"
  exit 2
elsif !Dir.exists?(year)
  puts "error: directory '#{year}' doesn't exist"
  exit 3
end

names = [
  "*.jpg", "*.jpeg", "*.JPG",
  "*.bmp", "*.BMP",
  "*.gif", "*.GIF",
  "*.mov", "*.MOV",
  "*.avi", "*.AVI",
  "*.3g*", "*.3G*"
]

for m in 1..12
  month = (m < 10 ? "0" : "") + m.to_s
  puts "#{month} = " + `find #{year} -name #{names.join(" -or -name ")} | grep #{year + month} | wc -l`
end
